---
- name: Install Docker and Jenkins on Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install required packages
      apt:
        name:
          - openjdk-11-jdk
          - docker.io
          - gnupg2
          - curl
        state: present
        force_apt_get: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add Jenkins apt key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        keyring: /usr/share/keyrings/jenkins-keyring.gpg
        state: present

    - name: Add Jenkins APT repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian-stable binary/"
        filename: "jenkins"
        state: present

    - name: Update apt after adding Jenkins repo
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        force_apt_get: yes

    - name: Ensure Jenkins user owns /var/lib/jenkins
      file:
        path: /var/lib/jenkins
        owner: jenkins
        group: jenkins
        recurse: yes

    - name: Enable and start Jenkins
      systemd:
        name: jenkins
        enabled: yes
        state: started
