---
- name: Install Docker and Jenkins
  hosts: all
  become: yes

  tasks:
    - name: Update yum cache
      yum:
        update_cache: yes

    - name: Install required packages
      yum:
        name:
          - docker
          - java-11-amazon-corretto
        state: present

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add Jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Wait before starting Jenkins (ensure Jenkins is installed cleanly)
      pause:
        seconds: 10

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable Jenkins
      systemd:
        name: jenkins
        enabled: yes

    - name: Start Jenkins with delay and fallback logging
      shell: |
        sleep 5
        systemctl start jenkins || (systemctl status jenkins && journalctl -xe)
      register: jenkins_status
      ignore_errors: yes

    - name: Show Jenkins service log if failed
      debug:
        var: jenkins_status.stdout_lines
      when: jenkins_status.rc != 0
